In [9]:
import numpy as np

In [15]:
l=(1,2,3,4,5,6)
a=np.array(l)

In [16]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
b=a[1:4]

In [18]:
b

array([2, 3, 4])

In [20]:
b[1:]=23

In [21]:
b


array([ 2, 23, 23])

In [22]:
a

array([ 1,  2, 23, 23,  5,  6])

In [24]:
#we see that making changes to b automatically changes the array a 
#this is beacuse when we created b it wasnt a coppy of a instead was an image of a
#thats why the changes in b is making changes in a 
#inorder to make a copy of the array we have an inbuilt function of numpy arrays 

In [25]:
c = a.copy()

In [26]:
c[2:]=34

In [27]:
c

array([ 1,  2, 34, 34, 34, 34])

In [28]:
a

array([ 1,  2, 23, 23,  5,  6])

In [ ]:
#notice no changes in a 