In [1]:
#matrices are 2 dimensional arrays
#first we come row(horizontal),then column(vertical)
#while specifiying a matrix we give 3 parameters
#first parameter is the data set
#second parameter is the oreder of matrix
#is order by which the data has to be filled
# we have c or f for that
#c is data is filled row wise 
#f is data is filled column wise

In [3]:
import numpy as np

In [8]:
mydata=np.arange(0,20) #to get some data in the form of array

In [9]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
#now we arrange it into matrix
matrix1=np.reshape(mydata,(4,5),order='C')

In [31]:
matrix1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
#now lets access 10

In [33]:
matrix1[2,0] #first we metion rwo then column #remember indexing starts from 0

10

In [34]:
#now lets do it woth order F

In [35]:
matrix2=np.reshape(mydata, (4,5), order='F')

In [36]:
matrix2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
#mydata is an array
#thus we can write like this directly
mydata.reshape((4,5),order='F')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])